### ISSUE TITLE
not indicated on same URL

### ISSUE THREAD

**Issue by immiProgrammer** [lexz451/next-nprogress#38]

**Comment by lexz451** [comment]
Hi @immiProgrammer. Could you elaborate on the issue so I can look into it? Thanks

**Comment by immiProgrammer** [comment]
In the past, I used [this](https://www.npmjs.com/package/nextjs-toploader) package. When a user clicks <a>, it will retrieve the href of the tag and match it with window.location. If the URL is the same, it will then start prograss and immediately complete.

It is effective for attracting users, but in your project, nothing happens when the URL is the same.

**Comment by lexz451** [comment]
HI @immiProgrammer I have released a new [version](https://github.com/lexz451/next-nprogress/releases/tag/v0.2.0) fixing the issue
